[project]
name = "agentic-cl-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.2.10",
    "langgraph>=1.0.8",
    "langsmith>=0.7.4",
    "python-dotenv>=1.2.1",
]
